/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SaveDataController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.CarreraModel;

/**
 *
 * @author delga
 */
public class CarreraView extends javax.swing.JFrame {

    CarreraModel carrera;

    /**
     * Creates new form CarreraView
     */
    public CarreraView(CarreraModel carreraModel) {
        carrera = carreraModel;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setIconImage(getToolkit().getImage(getClass().getResource("/assets/icono_carrera.png")));
        this.setTitle("Crear Carrera");

        if (carrera != null) {
            nombre.setText(carreraModel.getNombre());
            capacidad.setText(String.valueOf(carreraModel.getCapacidad()));
            nivelDificultad.setText(String.valueOf(carreraModel.getNivelDificultad()));
            isBajoTecho.setSelected(carreraModel.isIsTecho());
        } else {
            nombre.setText("");
            capacidad.setText("");
            nivelDificultad.setText("");
            isBajoTecho.setSelected(false);
        }

    }

    @Override
    public void dispose() {
        MainView.isCarreraOpen = false;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        capacidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nivelDificultad = new javax.swing.JTextField();
        isBajoTecho = new javax.swing.JCheckBox();
        guardarCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nombre:");

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nombre.setToolTipText("Ingrese el nombre de la carrera");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Capacidad:");

        capacidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        capacidad.setToolTipText("Ingrese la capacidad de personas");
        capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nivel de Dificultad: ");

        nivelDificultad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nivelDificultad.setToolTipText("Ingrese la dificultad de la carrera 0.0 - 10.0");

        isBajoTecho.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        isBajoTecho.setText("Se corre bajo techo");
        isBajoTecho.setIconTextGap(20);
        isBajoTecho.setMargin(new java.awt.Insets(10, 10, 10, 10));
        isBajoTecho.setVerifyInputWhenFocusTarget(false);
        isBajoTecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isBajoTechoActionPerformed(evt);
            }
        });

        guardarCarrera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        guardarCarrera.setText("Guardar");
        guardarCarrera.setPreferredSize(new java.awt.Dimension(114, 50));
        guardarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(capacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(nivelDificultad)
                            .addComponent(nombre))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isBajoTecho, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nivelDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(isBajoTecho, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(guardarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        isBajoTecho.getAccessibleContext().setAccessibleName("     Se corre bajo techo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void guardarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCarreraActionPerformed
        // TODO add your handling code here:

        try {
            String nombreValidacion = "";
            int capacidadValidacion = 0;
            double nivelValidacion = 0.0;
            
            //Dejar solo numeros
            nombreValidacion = nombre.getText().replaceAll("[\\PL]", "");
            System.out.println(nombreValidacion);
            nombre.setText(nombreValidacion);

            if (nombreValidacion.equals("") || nombreValidacion.isEmpty()) {
                throw new Exception("Por favor ingresar un nombre, el campo se encuentra sin diligenciar.");
            }
            if (nombreValidacion.length() > 30) {
                throw new Exception("El nombre no puede superar los 30 caracteres.");
            }

            try {
                capacidadValidacion = Integer.parseInt(capacidad.getText());
            } catch (Exception ex) {
                throw new Exception("Ingrese solo numeros en el campo de capacidad");
            }
            
            if(capacidadValidacion < 0){
                throw new Exception("Ingrese solo números positivos en el campo capacidad");
            }
            
            try {
                nivelValidacion = Double.parseDouble(nivelDificultad.getText());
            } catch (Exception ex) {
                throw new Exception("Ingrese solo numeros en el campo de nivel");
            }
            
            if(nivelValidacion < 0.0 || nivelValidacion > 10.0 ){
                throw new Exception("Ingrese solo un nivel en el rango 0.0 - 10.0");
            }

            int id = 0;

            if (carrera == null) {
                id = -1;
            } else {
                id = carrera.getIdCarrera();
            }

            carrera = new CarreraModel(id, nombre.getText(),
                    Integer.parseInt(capacidad.getText()),
                    Double.parseDouble(nivelDificultad.getText()),
                    isBajoTecho.isSelected());

            SaveDataController saveDataController = new SaveDataController();
            saveDataController.saveDataCarrera(carrera);
            MainView.updateTable();
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_guardarCarreraActionPerformed

    private void capacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadActionPerformed

    private void isBajoTechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isBajoTechoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isBajoTechoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacidad;
    private javax.swing.JButton guardarCarrera;
    private javax.swing.JCheckBox isBajoTecho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nivelDificultad;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
